image: go1com/ci-nodejs:node12

variables:
  AZURE_STORAGE_ACCOUNT: go1review

stages:
  - build
  - test
  - visual-test
  - release
  - npm-release

build:
  stage: build
  script:
    - yarn config set no-progress
    - yarn install --silent
    # Use concurrently to run job
    - yarn "ci:build"
    - cd "docs-site"
    - yarn install --frozen-lockfile
    - yarn "next:build:ci"
  artifacts:
    paths:
      - node_modules
      - build
      - docs-site/out
      - dist_storybook
    expire_in: 6h
  except:
    - "tags"
  only: ["branches"]

review:
  image: mcr.microsoft.com/azure-cli
  stage: test
  script:
    - az storage blob upload-batch -s ./dist_storybook -d '$web' --destination-path $CI_ENVIRONMENT_SLUG
  environment:
    name: go1d/$CI_COMMIT_REF_NAME
    url: https://go1review.z8.web.core.windows.net/$CI_ENVIRONMENT_SLUG/
    on_stop: stop_review
  only: ["branches"]
  except:
    - master

stop_review:
  image: mcr.microsoft.com/azure-cli
  stage: test
  script:
    - az storage blob delete-batch -s '$web' --pattern ${CI_ENVIRONMENT_SLUG}/*
  variables:
    GIT_STRATEGY: none
  dependencies: []
  when: manual
  environment:
    name: go1d/$CI_COMMIT_REF_NAME
    action: stop
  only: ["branches"]
  except:
    - master

test:linting:
  stage: test
  script: yarn run tslint
  except:
    - master
    - tags

test:unit:
  stage: test
  needs: []
  script:
    - yarn config set no-progress
    - yarn install --frozen-lockfile --silent
    - yarn test --no-cache --coverage
  artifacts:
    paths:
      - coverage
    expire_in: 1h
  except:
    - "tags"

visual-test:happo:
  stage: visual-test
  dependencies:
    - test:linting
  allow_failure: true
  before_script:
    - export PREVIOUS_SHA=`git rev-parse origin/master`
    - export CURRENT_SHA=$CI_COMMIT_SHA
    - export CHANGE_URL=$CI_PAGES_URL
  script:
    - DIFF_REVIEW=$(node ./scripts/check-screenshot-result.js)
    - if [ "$DIFF_REVIEW" != "accept" ]; then
    - yarn config set no-progress
    - yarn install --silent
    - yarn run happo-ci
    # Check for EXIT_CODE env
    - NPM_BIN=$(yarn bin)
    - SUMMARY=$("$NPM_BIN"/happo compare "$PREVIOUS_SHA" "$CURRENT_SHA");
    - if [ "$EXIT_CODE" == "113" ]; then exit 1; fi; fi
  except:
    - master
    - tags

pages: # NEVER rename this. I must apparently be exactly this to work
  stage: release
  dependencies:
    - build
  script:
    - rm -rf public
    - mkdir public
    - mkdir public/storybook
    - cp -r docs-site/out/* public/
    - cp -r dist_storybook/* public/storybook/

  artifacts:
    paths:
      - public # mandatory, other folder won't work
  except:
    - "tags"
  only:
    - master

release:npm:
  stage: npm-release
  dependencies:
    - build
  before_script:
    - "which ssh-agent || ( apk add -uUv openssh-client)"
    - eval $(ssh-agent -s)
    - echo "$GO1D_PRIVATE_SSH_KEY" |  base64 --decode | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan code.go1.com.au >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - git clone git@code.go1.com.au:${CI_PROJECT_PATH}.git
    - cp -r build ${CI_PROJECT_NAME}/
    - cd ${CI_PROJECT_NAME}
    - git config user.name "$GITLAB_USER_NAME"
    - git config user.email "$GITLAB_USER_EMAIL"
    - git checkout $CI_COMMIT_REF_NAME
    - git branch --set-upstream-to origin/$CI_COMMIT_REF_NAME
    - npm config set scope go1d --global
    - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}'>.npmrc
    - rm readme.md
    - mv npm-readme.md readme.md
    - yarn config set no-progress
    - yarn install --silent
    - yarn changeset status || yarn changeset add --empty
    - yarn changeset version
    - git add package.json .changeset/ CHANGELOG.md
    - git commit -m "[NPM-CI] Version packages [skip ci]" || true # [skip ci] prevents infinite loop
    - yarn changeset publish || true # creates a git tag, and must be preceded by the version commit
    - git push -o ci.skip git@${CI_SERVER_HOST}:${CI_PROJECT_PATH}.git --follow-tags || true
    - NPM_BIN=$(yarn bin)
    - MASTER_SHA=$(git rev-parse origin/master)
    - if ! "$NPM_BIN"/happo has-report "$MASTER_SHA"; then
    - yarn happo run $MASTER_SHA; fi
  artifacts:
    paths:
      - package.json
      - .changeset/
      - CHANGELOG.md
    when: on_failure
  except:
    - "tags"
  only:
    - master
