image: go1com/ci-nodejs:node8

cache:
  paths:
    - node_modules/

stages:
  - test

test:unit:
  stage: test
  tags: ["aws"]
  script:
    - yarn install
    - yarn test --coverage --runInBand
  artifacts:
    paths:
      - coverage
    expire_in: 1h
  except:
    - "tags"
