image: go1com/ci-nodejs:node8

cache:
  paths:
    - node_modules/

stages:
  - build
  - test
  - release
  - npm-release

build:
  stage: build
  tags: ["aws"]
  cache:
    paths: [node_modules]
    key: "$CI_PROJECT_ID"
  script:
    - yarn config set no-progress
    - yarn install --silent
    - yarn "npm:build"
    - yarn "docs:build"
    - yarn "storybook:build"
  artifacts:
    paths:
      - node_modules
      - build
      - dist
      - dist_storybook
    expire_in: 6h
  except:
    - "tags"
  only:
    - master

build-dev:
  stage: build
  tags: ["aws"]
  cache:
    paths: [node_modules]
    key: "$CI_PROJECT_ID"
  script:
    - yarn config set no-progress
    - yarn install --silent
    - yarn "npm:build"
  artifacts:
    paths:
      - node_modules
      - build
      - dist
    expire_in: 6h
  only: ["branches"]
  except:
    - master

test:linting:
  stage: test
  tags: ["aws"]
  script: yarn tslint

test:unit:
  stage: test
  tags: ["aws"]
  script:
    - yarn config set no-progress
    - yarn install --silent
    - yarn test --coverage --runInBand
  artifacts:
    paths:
      - coverage
    expire_in: 1h
  except:
    - "tags"

test:happo:
  stage: test
  tags: ["aws"]
  allow_failure: true
  before_script:
    - export PREVIOUS_SHA=`git rev-parse origin/master`
    - export CURRENT_SHA=$CI_COMMIT_SHA
    - export CHANGE_URL=$CI_PAGES_URL
  script:
    - DIFF_REVIEW=$(node ./scripts/check-screenshot-result.js)
    - if [ "$DIFF_REVIEW" != "accept" ]; then
    - yarn config set no-progress
    - yarn install --silent
    - yarn react:docs && node ./.storybook/generate-props-file.js
    - yarn run happo-ci
    # Check for EXIT_CODE env
    - NPM_BIN=$(yarn bin)
    - SUMMARY=$("$NPM_BIN"/happo compare "$PREVIOUS_SHA" "$CURRENT_SHA");
    - if [ "$EXIT_CODE" == "113" ]; then exit 1; fi; fi
  only:
  - merge_requests

pages: # NEVER rename this. I must apparently be exactly this to work
  stage: release
  tags: ["aws"]
  dependencies:
    - build
  script:
    - rm -rf public
    - mkdir public
    - rm -rf public/storybook
    - mkdir public/storybook
    - cp -r dist/* public/
    - cp -r dist_storybook/* public/storybook/

  artifacts:
    paths:
      - public # mandatory, other folder won't work
  except:
    - "tags"
  only:
    - master

release:npm:
  stage: npm-release
  tags: ["aws"]
  dependencies:
    - build
  before_script:
    - 'which ssh-agent || ( apk add -uUv openssh-client)'
    - eval $(ssh-agent -s)
    - echo "$GO1D_PRIVATE_SSH_KEY" |  base64 --decode | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan code.go1.com.au >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - git clone git@code.go1.com.au:${CI_PROJECT_PATH}.git
    - cp -r build ${CI_PROJECT_NAME}/
    - cd ${CI_PROJECT_NAME}
    - git config user.name "$GITLAB_USER_NAME"
    - git config user.email "$GITLAB_USER_EMAIL"
    - git checkout $CI_COMMIT_REF_NAME
    - git branch --set-upstream-to origin/$CI_COMMIT_REF_NAME
    - PACKAGE_VERSION=$(npm version patch -m "[NPM-CI] Publishing Version %s to NPM [skip ci]")
    - git push origin
    - git push origin $PACKAGE_VERSION
    - npm config set scope go1d --global
    - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}'>.npmrc
    - rm readme.md
    - mv npm-readme.md readme.md
    - npm publish --access public
    - NPM_BIN=$(yarn bin)
    - MASTER_SHA=$(git rev-parse origin/master`)
    - if ! "$NPM_BIN"/happo has-report "$MASTER_SHA"; then
    - yarn happo run $MASTER_SHA; fi
  except:
    - "tags"
  only:
    - master
