image: go1com/ci-nodejs:node8

cache:
  paths:
  - node_modules/

stages:
  - build
  - test
  - release

build:
  stage: build
  tags: ["aws"]
  cache:
    paths: [node_modules]
    key: "$CI_PROJECT_ID"
  script:
    - yarn install
    - yarn tsc
    - yarn generate-proptypes
    - yarn x0 build docs
  artifacts:
    paths:
      - node_modules
      - build
      - dist
    expire_in: 6h
  only: ["branches"]

test:linting:
  stage: test
  tags: ["aws"]
  script: yarn tslint


release:pages:
  stage: release
  tags: ["aws"]
  script:
    - mkdir public
    - cp -r dist/* public/
  artifacts:
    paths:
      - public # mandatory, other folder won't work
  except:
    - $CI_COMMIT_MESSAGE =~ /npm release/
  # only:
  #   - master # or dev, the branch you want to publish
    - node_modules/
test:unit:
  stage: test
  tags: ["aws"]
  script:
    - yarn install
    - yarn test --coverage --runInBand
  artifacts:
    paths:
      - coverage
    expire_in: 1h
  except:
    - "tags"


release:npm:
  stage: release
  tags: ["aws"]
  script:
    - npm version patch
    - git add package.json
    - git commit -m "[npm release] Bumping package version"
    - git push origin head
  except:
    - $CI_COMMIT_MESSAGE =~ /npm release/
